name: Validate AZD template
on:
  push:
    branches: [ main ]
    paths:
      - "infra/**"
  pull_request:
    branches: [ main ]
    paths:
      - "infra/**"
  workflow_dispatch:

jobs:
  templateanalyzer:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Bicep for linting
        uses: azure/CLI@v2
        with:
          inlineScript: az config set bicep.use_binary_from_path=false && az bicep build -f infra/main.bicep --stdout

      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@preview
        id: msdo
        continue-on-error: true
        with:
          tools: templateanalyzer

      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: github.repository == 'Azure-Samples/azure-search-openai-demo'
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
  psrule:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Run analysis by using the PSRule GitHub action.
      - name: Run PSRule analysis
        uses: microsoft/ps-rule@v2.9.0
        with:
          modules: PSRule.Rules.Azure
          inputPath: infra/main.test.bicep
          outputFormat: Sarif
          outputPath: reports/ps-rule-results.sarif
          summary: true
        env:
          PSRULE_CONFIGURATION_AZURE_BICEP_FILE_EXPANSION: true

      - name: Upload results to security tab
        uses: github/codeql-action/upload-sarif@v3
        if: github.repository == 'Azure-Samples/azure-search-openai-demo'
        with:
          sarif_file: reports/ps-rule-results.sarif
